name: DataFactory-CICD-Pipeline-$(Date:yyyyMMdd)$(Rev:.r)

# ADF is the shortened version of Azure Data Factory

trigger: none
# - main # Will trigger the pipeline after a commit to the main branch. Can update to trigger: none to only run the pipeline manually.

pool:
  vmImage: "windows-latest"

stages:
- stage: BuildDEVDataFactory
  displayName: "Build DEV Data Factory"
  
  variables:
  - template: variables/dev-variables.yml

  jobs:
  - job: ValidateAndBuildDataFactoryTemplate
    displayName: "Build DEV Data Factory"
    steps:
    - template: adf-cicd/adf-build.yml
      parameters:
        DataFactoryName: "${{ variables.BuildDataFactoryName }}"
        ResourceGroupName: "${{ variables.BuildDataFactoryResourceGroupName }}"
        ADFArtifactName: "${{ variables.ADFArtifactName }}"
        WorkingDirectory: "${{ variables.WorkingDirectory }}"


    - task: DownloadPipelineArtifact@2
      displayName: "Download The ADF Artifact"
      inputs:
        buildType: "current"
        artifactName: "${{ variables.ADFArtifactName }}"
        targetpath: "$(Pipeline.Workspace)/${{ variables.ADFArtifactName }}"
    

    - task: AzureCLI@2
      displayName: 'Create Template Specs for ADF Linked ARM Templates'
      inputs:
        azureSubscription: 'DataFactoryCICDAzureResourceManager'
        scriptType: 'pscore'
        targetType: 'filePath'
        scriptLocation: 'scriptPath'
        scriptPath: '${{ variables.WorkingDirectory }}/cicd/new-linked-template/new-linked-template-create-deploy.ps1' # $(System.DefaultWorkingDirectory)/cicd/... also works
        arguments: "-FolderPathADFLinkedARMTemplates '$(Pipeline.Workspace)/${{ variables.ADFArtifactName }}/linkedTemplates' 
                    -DeployTemplateSpecsResourceGroupName '${{ variables.DeployTemplateSpecsResourceGroupName }}' 
                    -DeployTemplateSpecsResourceGroupLocation '${{ variables.DeployTemplateSpecsResourceGroupLocation }}' 
                    -TemplateSpecsVersionNumber '${{ variables.TemplateSpecsVersionNumber }}'
                    -OutputFolderPathNewADFMasterARMTemplate  '${{ variables.WorkingDirectory }}'"
                    # FolderPathADFLinkedARMTemplates is where the pipeline stores the Data Factory (ADF) linked ARM Templates
     
    
# DEPLOY TO UAT
- stage: DeployToUAT
  dependsOn: BuildDEVDataFactory
  condition: succeeded()
  displayName: "Deploy To UAT"

  variables:
  - template: variables/uat-variables.yml

  jobs:
  # - deployment: ApprovalCheckDeployToUAT
  #   displayName: "Approval Check To Deploy To UAT"
  #   environment: UAT
  #   strategy:
  #     runOnce:
  #       deploy:
  #         steps:
  #         - powershell: |
  #             Write-Host "Deploy To UAT has been fully approved. Starting the deployment to UAT."
  
  # - job: DeployAzureResources
  #   displayName: "Deploy Azure Resources Via Bicep"
  #   steps:
  #   - template: azure-resources/deploy-azure-resources.yml
  #     parameters:
  #       AzureResourceManagerConnection: "${{ variables.AzureResourceManagerConnection }}"
  #       DataFactoryName: "${{ variables.DataFactoryName }}"
  #       ADFResourceGroupName: "${{ variables.ADFResourceGroupName }}"
  #       ADFBicepTemplateFilePath: "${{ variables.ADFBicepTemplateFilePath }}"
        # KeyVaultName: "${{ variables.KeyVaultName }}"
        # KeyVaultResourceGroupName: "${{ variables.KeyVaultResourceGroupName }}"
        # KeyVaultURL: "${{ variables.KeyVaultURL }}"
        # KeyVaultBicepTemplateFilePath: "${{ variables.KeyVaultBicepTemplateFilePath }}"

  - job: DeployDataFactory
    displayName: "Deploy ADF ARM Template To Target ADF"
    # dependsOn: DeployAzureResources
    # condition: succeeded()
    steps:
    - task: AzureCLI@2
      displayName: 'Deploy To UAT ADF'
      inputs:
        azureSubscription: 'DataFactoryCICDAzureResourceManager'
        scriptType: 'pscore'
        targetType: 'filePath'
        scriptLocation: 'inlineScript'
        inlineScript: |
          Write-Host "Attempting to retrieve the resource ID for the new ARMTemplateV2_master Template Spec"
          $TemplateSpecResourceID = $(az ts show --name NewARMTemplateV2_master --resource-group rg-adf-cicd-linked-uat --version "1.0.0.0" --query "id")

          Write-Host "Successfully retrieved the resource ID for the new master Spec Template"

          Write-Host "Attempting to deploy the master linked Template Spec to Data Factory ${{ variables.DataFactoryName }}. This may take a couple of mins."
          az deployment group create --resource-group rg-adf-cicd-linked-uat --template-spec $TemplateSpecResourceID --parameters factoryName='adf-linked-templates-njl-uat' --output none
          Write-Host "Successfully deployed to Data Factory ${{ variables.DataFactoryName }}"

    
    # Uncomment this task if you want to delete all of the Template Specs that were created.
    # - task: AzureCLI@2
    #   displayName: 'Optionally Delete All of the Template Specs'
    #   inputs:
    #     azureSubscription: 'DataFactoryCICDAzureResourceManager'
    #     scriptType: 'pscore'
    #     targetType: 'filePath'
    #     scriptLocation: 'inlineScript'
    #     inlineScript: |
    #       Write-Host "Attempting to delete all of the Template Specs"
    #       az group delete -name rg-adf-cicd-linked-uat --force-deletion-types Microsoft.Resources/templateSpecs --yes

    #       Write-Host "Successfully deleted all of the Template Specs"
    
    
    
    
    
    - template: adf-cicd/adf-deploy.yml
      parameters:
        AzureResourceManagerConnection: "${{ variables.AzureResourceManagerConnection }}"
        DataFactoryName: "${{ variables.DataFactoryName }}"
        DataFactoryTemplateParametersFilePath: "${{ variables.DataFactoryTemplateParametersFilePath }}"
        ResourceGroupName: "${{ variables.ADFResourceGroupName }}"
        ResourceGroupLocation: "${{ variables.ResourceGroupLocation }}"
        ADFArtifactName: "${{ variables.ADFArtifactName }}"
        Environment: "${{ variables.Environment }}"

# # DEPLOY TO PROD
# - stage: DeployToPROD
#   dependsOn: 
#     - BuildDEVDataFactory
#     - DeployToUAT 
#   condition: succeeded()
#   displayName: "Deploy To PROD"

#   variables:
#   - template: variables/prod-variables.yml

#   jobs:
#   # - deployment: ApprovalCheckDeployToPROD
#   #   displayName: "Approval Check To Deploy To PROD"
#   #   environment: PROD
#   #   strategy:
#   #     runOnce:
#   #       deploy:
#   #         steps:
#   #         - powershell: |
#   #             Write-Host "Deploy To PROD has been fully approved. Starting the deployment to PROD."
  
#   - job: DeployAzureResources
#     displayName: "Deploy Azure Resources Via Bicep"
#     steps:
#     - template: azure-resources/deploy-azure-resources.yml
#       parameters:
#         AzureResourceManagerConnection: "${{ variables.AzureResourceManagerConnection }}"
#         DataFactoryName: "${{ variables.DataFactoryName }}"
#         ADFResourceGroupName: "${{ variables.ADFResourceGroupName }}"
#         ADFBicepTemplateFilePath: "${{ variables.ADFBicepTemplateFilePath }}"
#         # KeyVaultName: "${{ variables.KeyVaultName }}"
#         # KeyVaultResourceGroupName: "${{ variables.KeyVaultResourceGroupName }}"
#         # KeyVaultURL: "${{ variables.KeyVaultURL }}"
#         # KeyVaultBicepTemplateFilePath: "${{ variables.KeyVaultBicepTemplateFilePath }}"

#   - job: DeployDataFactory
#     displayName: "Deploy ADF ARM Template To Target ADF"
#     dependsOn: DeployAzureResources
#     condition: succeeded()
#     steps:
#     - template: adf-cicd/adf-deploy.yml
#       parameters:
#         AzureResourceManagerConnection: "${{ variables.AzureResourceManagerConnection }}"
#         DataFactoryName: "${{ variables.DataFactoryName }}"
#         DataFactoryTemplateParametersFilePath: "${{ variables.DataFactoryTemplateParametersFilePath }}"
#         ResourceGroupName: "${{ variables.ADFResourceGroupName }}"
#         ResourceGroupLocation: "${{ variables.ResourceGroupLocation }}"
#         ADFArtifactName: "${{ variables.ADFArtifactName }}"
#         Environment: "${{ variables.Environment }}"





    # - task: CmdLine@2
    #   displayName: 'List All Files and directories'
    #   inputs:
    #     script: |
    #       echo "Structure of work folder of this pipeline:"
    #       tree $(Agent.WorkFolder)\1 /f

    #       echo "Build.ArtifactStagingDirectory:" 

    #       echo "$(Build.ArtifactStagingDirectory)"

    #       echo "Build.BinariesDirectory:" 

    #       echo "$(Build.BinariesDirectory)"

    #       echo "Build.SourcesDirectory:"

    #       echo "$(Build.SourcesDirectory)"




























